### ISSUE TITLE
Remove reliance on vsphere-automation sdk fork

### ISSUE THREAD

**Issue by brakthehack** [vmware-tanzu/nsx-operator#309]
Currently nsx-operator replaces the vsphere-automation-sdk with a fork. This fork does not contain the same versions as its upstream counterpart. As a result, when one tries to import nsx-operator into a go project, we are greeted with the following errors:

```
go: github.com/vmware/vsphere-automation-sdk-go/[lib@v0.5.2](mailto:lib@v0.5.2): invalid version: unknown revision lib/v0.5.2
go: github.com/vmware/vsphere-automation-sdk-go/[runtime@v0.5.2](mailto:runtime@v0.5.2): invalid version: unknown revision runtime/v0.5.2
```

The workaround is that downstream projects need to add the following configuration into their repo to properly sync modules:

```
replace (
  github.com/vmware/vsphere-automation-sdk-go/lib => github.com/TaoZou1/vsphere-automation-sdk-go/lib v0.5.2
  github.com/vmware/vsphere-automation-sdk-go/runtime => github.com/TaoZou1/vsphere-automation-sdk-go/runtime v0.5.2
)
```

Ideally, this project should just move back onto the mainline repo. If this isn't possible, do not use the replace directive for dependencies. Use the fork directly so that transitive dependencies can be correctly calculated.

**Comment by TaoZou1** [comment]
Hi, 
This replace directive has been deleted since SDK has official release which supports 4.1.2.
