### ISSUE TITLE
pkg/api should be made sub go module so it can be consumed by other project

### ISSUE THREAD

**Issue by lubronzhan** [vmware-tanzu/nsx-operator#372]
Right now if other project wants to consume pkg/api it needs to pull the whole project through go module, it's unnecessary and might cause conflict. We ran into this issue when importing the api into cloud-provider-vsphere cc @wyike

Example PR https://github.com/vmware-tanzu/tanzu-framework/pull/2216 done by @akutz to make some package as sub go module in tanzu-framework

**Comment by wyike** [comment]
Same requests on https://github.com/vmware-tanzu/nsx-operator/tree/vpc_dev/pkg/client. 

Both pkg/api and pkg/client should be able to imported as sub go module if other projects wants to consume.

**Comment by wyike** [comment]
In the api, we'd better removing the controller-runtime dependency like https://github.com/kubernetes-sigs/cluster-api/pull/9045, otherwise it will be introduced to other project and very easy to cause conflict.

**Comment by wyike** [comment]
cc @zhengxiexie @dantingl  FYI an follow up request on supporting apis, clients in nsx-operator

**Comment by wyike** [comment]
I noticed nsx-operator/pkg/apis is already a go submodule on [vpc_dev ](https://github.com/vmware-tanzu/nsx-operator/tree/vpc_dev/pkg/apis) branch. 

Regarding https://github.com/vmware-tanzu/nsx-operator/tree/vpc_dev/pkg/apis, highly suggest to remove controller-runtime dependency in future like https://github.com/kubernetes-sigs/cluster-api/pull/9045.

Could we do the same for  https://github.com/vmware-tanzu/nsx-operator/tree/vpc_dev/pkg/apis/nsx.vmware.com and https://github.com/vmware-tanzu/nsx-operator/tree/vpc_dev/pkg/client.

**Comment by lubronzhan** [comment]
Good suggestion. Let me close this then, could you create one for removing dependency of controller-runtime.

>Could we do the same [vpc_dev/pkg/client](https://github.com/vmware-tanzu/nsx-operator/tree/vpc_dev/pkg/client?rgh-link-date=2023-10-30T05%3A49%3A06Z) and [vpc_dev/pkg/apis/nsx.vmware.com](https://github.com/vmware-tanzu/nsx-operator/tree/vpc_dev/pkg/apis/nsx.vmware.com?rgh-link-date=2023-10-30T05%3A49%3A06Z), thanks!

It's ok not to submodule client I think. Even though it might introduce different controller-runtime version, maybe better bump the controller runtime in vpc_dev.

Do you need to add go.mod for nsx.vmware.com separately? It's already under pkg/apis

**Comment by wyike** [comment]
> Do you need to add go.mod for nsx.vmware.com separately? It's already under pkg/apis
I thought if pkg/apis controller-runtime dependency cannot be removed in a short time, we can just import pkg/apis/nsx.vmware.com. (I am also do some test to see if this is required)

> It's ok not to submodule client I think.
curious if not to submodule client, how can other project use it, except to import the whole nsx-operator.

**Comment by zhengxiexie** [comment]
https://github.com/vmware-tanzu/nsx-operator/pull/374
fixed here.
