### ISSUE TITLE
Local replacements causes downstream builds to fail

### ISSUE THREAD

**Issue by brakthehack** [vmware-tanzu/nsx-operator#460]
Hi, we have another similar occurrence to #309 . This time the offending commits have packages with local code:

https://github.com/vmware-tanzu/nsx-operator/commit/c0c1d166de5d47f85db0be9c9f8bd09187942991
https://github.com/vmware-tanzu/nsx-operator/commit/585b431da40e1c571be1c40a8477abdb868a581b

This breaks consumers because they too must make the replacement. However, the replacement is actually impossible in this case. Please stop using replacements to solve dependency issues since they are not transitive.

cc @jwsui @timdengyun

**Comment by timdengyun** [comment]
This issue is resolved after merging PR: https://github.com/vmware-tanzu/nsx-operator/pull/527 
Thanks @jwsui
