### ISSUE TITLE
nsx/client GetClient  can't be triggered twice

### ISSUE THREAD

**Issue by zhengxiexie** [vmware-tanzu/nsx-operator#514]
if GetClient repeatdly, it would report error

2024-02-04 03:19:37.781	ERROR	util/utils.go:250	handle http response	{"status": 403, "requestUrl": "https://10.221.156.13/api/v1/node/version", "response body": "{\"module_name\":\"common-service\",\"error_message\":\"Bad XSRF token\",\"error_code\":98}", "error": "received HTTP Error"}
github.com/vmware-tanzu/nsx-operator/pkg/nsx/util.HandleHTTPResponse
	/root/nsx-operator/pkg/nsx/util/utils.go:250
github.com/vmware-tanzu/nsx-operator/pkg/nsx.(*Cluster).GetVersion
	/root/nsx-operator/pkg/nsx/cluster.go:351
github.com/vmware-tanzu/nsx-operator/pkg/clean.httpQueryDLBResources
	/root/nsx-operator/pkg/clean/clean_dlb.go:55
github.com/vmware-tanzu/nsx-operator/pkg/clean.CleanDLB
	/root/nsx-operator/pkg/clean/clean_dlb.go:77
github.com/vmware-tanzu/nsx-operator/pkg/clean.Clean.func2
	/root/nsx-operator/pkg/clean/clean.go:66
k8s.io/client-go/util/retry.OnError.func1
	/root/go/pkg/mod/k8s.io/client-go@v0.28.4/util/retry/util.go:51
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection
	/root/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/wait.go:145
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
	/root/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/backoff.go:461
k8s.io/client-go/util/retry.OnError
	/root/go/pkg/mod/k8s.io/client-go@v0.28.4/util/retry/util.go:50
github.com/vmware-tanzu/nsx-operator/pkg/clean.Clean
	/root/nsx-operator/pkg/clean/clean.go:59
main.main
	/root/nsx-operator/cmd_clean/main.go:92
runtime.main
	/usr/local/go/src/runtime/proc.go:267

**Comment by TaoZou1** [comment]
There is a jarCache   = NewJar() in cluster.go which never think there would be more than one cluster. so two clusters will share the same jarCache.
Currently there is no such requirement to support more than one cluster.
Please reopen it if such requirement needed.
